[general]
live_config_reload = true

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
startup_mode = "Windowed"
dimensions = { columns = 40, lines = 80 }

[font]
normal = { family = "FiraCode Nerd Font Propo", style = "Regular" }
bold = { family = "FiraCode Nerd Font Propo", style = "Bold" }
italic = { family = "FiraCode Nerd Font Propo", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Propo", style = "Bold Italic" }
size = 16

[cursor]
style.blinking = "On"
blink_timeout = 10
blink_interval = 550

# Default colors
[colors.primary]
background = "#3C3836"
foreground = "#FBF1C7"

dim_foreground    = "#F8E7A0"
bright_foreground = "#FDF5D8"

# Cursor colors
[colors.cursor]
text   = "#2c2c2c"
cursor = "#d9d9d9"

# Normal colors
[colors.normal]
black   = "#1c1c1c"
red     = "#B31F19"
green   = "#7A7A15"
yellow  = "#D79921"
blue    = "#458588"
magenta = "#B16286"
cyan    = "#689D6A"
white   = "#FDF5D8"

# Bright colors
[colors.bright]
black   = "#636363"
red     = "#bc5653"
green   = "#909d63"
yellow  = "#ebc17a"
blue    = "#7eaac7"
magenta = "#aa6292"
cyan    = "#86d3ce"
white   = "#f7f7f7"

# Dim colors
[colors.dim]
black   = "#232323"
red     = "#74423f"
green   = "#5e6547"
yellow  = "#8b7653"
blue    = "#556b79"
magenta = "#6e4962"
cyan    = "#5c8482"
white   = "#828282"


[keyboard]
bindings = [
    { "action" = "ToggleViMode", "key" = "v", "mods" = "Command | Control | Option | Shift" },
    { "action" = "ReceiveChar", "key" = "t", "mods" = "Command" },
    { "action" = "None", "key" = "t", "mods" = "Command" }
]
